### ISSUE TITLE
[BUG] fails to build with native dependency `VideoLAN.LibVLC.Windows`: `PEFileNotSupportedException: PE file does not contain any managed metadata`

### ISSUE THREAD

**Issue by Felk** [reactiveui/Pharmacist#226]
**Describe the bug**
Pharmacist causes the build to fail if a nuget package containing native code is listed as a dependency;
```csproj
<PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.12" />
```

The exception during `dotnet build`:
```
Pharmacist.MSBuild.targets(48, 5): PharmacistNuGetTask: ICSharpCode.Decompiler.Metadata.PEFileNotSupportedException: PE file does not contain any managed metadata.
  at ICSharpCode.Decompiler.Metadata.PEFile..ctor(String fileName, PEReader reader, MetadataReaderOptions metadataOptions) in D:\a\Pharmacist\Pharmacist\src\ICSharpCode.Decompiler\Metadata\PEFile.cs:line 68
  at ICSharpCode.Decompiler.Metadata.PEFile..ctor(String fileName, PEStreamOptions streamOptions, MetadataReaderOptions metadataOptions) in D:\a\Pharmacist\Pharmacist\src\ICSharpCode.Decompiler\Metadata\PEFile.cs:line 54
  at Pharmacist.Core.Generation.Compilation.EventBuilderCompiler.<>c.<.ctor>b__3_1(String x) in D:\a\Pharmacist\Pharmacist\src\Pharmacist.Core\Generation\Compilation\EventBuilderCompiler.cs:line 50
  at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
  at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
  at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
  at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
  at Pharmacist.Core.Generation.Compilation.EventBuilderCompiler..ctor(InputAssembliesGroup input, NuGetFramework framework) in D:\a\Pharmacist\Pharmacist\src\Pharmacist.Core\Generation\Compilation\EventBuilderCompiler.cs:line 52
  at Pharmacist.Core.ObservablesForEventGenerator.ExtractEventsFromAssemblies(TextWriter writer, InputAssembliesGroup input, NuGetFramework framework) in D:\a\Pharmacist\Pharmacist\src\Pharmacist.Core\ObservablesForEventGenerator.cs:line 324
  at Pharmacist.Core.ObservablesForEventGenerator.ExtractEventsFromNuGetPackages(TextWriter writer, IReadOnlyCollection`1 packages, IReadOnlyCollection`1 frameworks, String packageOutputFolder) in D:\a\Pharmacist\Pharmacist\src\Pharmacist.Core\ObservablesForEventGenerator.cs:line 144
  at Pharmacist.MsBuild.NuGet.PharmacistNuGetTask.Execute() in D:\a\Pharmacist\Pharmacist\src\Pharmacist.MsBuild.NuGet\PharmacistNuGetTask.cs:line 117
```

Adding `<ExcludeAssets>buildTransitive</ExcludeAssets>` additionally to `<PrivateAssets>all</PrivateAssets>` fixes the build problem, but then Pharmacist just doesn't generate the `Events()` extension methods either.

**Steps To Reproduce**
1. Add a nuget dependency on a package containing native code. In my case:
   ```csproj
   <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.12" />
   ```
2. build the project
It will fail with the above error

**Expected behavior**
the presence of native libraries would not cause the build to fail.

**Environment**
- Windows 10 20H2
- dotnet 5.0.202
- Pharmacist 2.0.8

**Comment by glennawatson** [comment]
See https://www.nuget.org/packages/ReactiveMarbles.ObservableEvents.SourceGenerator/ and https://github.com/reactivemarbles/ObservableEventsSourceGenerator

This won't scan native DLLs, only instances of classes you'll use.
